### ISSUE TITLE
Markup Design of the App

### ISSUE THREAD

**Issue by timkao** [timkao/ParQ#3]

**Comment by gabriela229** [comment]
[Doc - Nov 2 2017 - 7-37 PM.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55a7b37118e4a11f009d9441/125516c66e82c728ace21e0d46cc9b9963cfc38780ffff11e40fa0c57e066a337e49f07c30b5ce6af3006b1300051bff054a5556f9f0df2daeb56a24d85a59b9d66d5f74c23b10afb0d11bba13a632c91edbe2e3d7158abd7f37ed998e48341f001880f95b3da7914dcc5ef059ac.pdf)
